#!/usr/bin/env python3
"""
Reads pywal colors and regenerates waybar/colors.css.
Pass --restart to also kill and relaunch waybar (used by walset).
"""

import json
import os
import subprocess

COLORS_CSS = os.path.expanduser("~/.config/waybar/colors.css")
WAL_JSON   = os.path.expanduser("~/.cache/wal/colors.json")


def hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def rgba(h: str, a: float) -> str:
    r, g, b = hex_to_rgb(h)
    return f"rgba({r}, {g}, {b}, {a:.2f})"


def load_colors():
    with open(WAL_JSON) as f:
        wal = json.load(f)
    return {
        "bg":      wal["special"]["background"],
        "fg":      wal["special"]["foreground"],
        "accent":  wal["colors"]["color2"],
        "dim":     wal["colors"]["color8"],
        "muted":   wal["colors"]["color3"],
        "subtle":  wal["colors"]["color5"],
    }


def build_css(c: dict) -> str:
    return f"""\
/* Auto-generated by waybar/wal-reload.sh — do not edit manually */

@define-color wal_bg              {c['bg']};
@define-color wal_bg_module       {rgba(c['bg'], 0.88)};
@define-color wal_fg              {c['fg']};
@define-color wal_dim             {c['dim']};
@define-color wal_muted           {c['muted']};
@define-color wal_subtle          {c['subtle']};
@define-color wal_accent          {c['accent']};
@define-color wal_accent_soft     {rgba(c['accent'], 0.18)};
@define-color wal_accent_hover    {rgba(c['accent'], 0.30)};
@define-color wal_dim_soft        {rgba(c['dim'],    0.15)};
@define-color wal_dim_hover       {rgba(c['dim'],    0.26)};
@define-color wal_muted_soft      {rgba(c['muted'],  0.15)};
@define-color wal_muted_hover     {rgba(c['muted'],  0.26)};
@define-color wal_fg_soft         {rgba(c['fg'],     0.12)};
@define-color wal_fg_hover        {rgba(c['fg'],     0.20)};
@define-color wal_red             #ff5555;
@define-color wal_red_soft        rgba(255, 85, 85, 0.20);
@define-color wal_green           #a3be8c;
"""


def restart_waybar():
    subprocess.run(["pkill", "waybar"], capture_output=True)
    subprocess.Popen(
        ["waybar"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


if __name__ == "__main__":
    import sys
    try:
        colors = load_colors()
        css = build_css(colors)
        with open(COLORS_CSS, "w") as f:
            f.write(css)
        if "--restart" in sys.argv:
            restart_waybar()
            print("waybar reloaded with new pywal colors.")
        else:
            print("waybar colors.css updated.")
    except Exception as e:
        print(f"wal-reload: {e}")
