background {
    monitor = eDP-1
    path = /home/krish/Pictures
    blur_passes = 3
    brightness = 0.7
}

input-field {
    monitor = eDP-1
    size = 200, 50
    position = 0, -100
    outline_thickness = 2
    inner_color = rgba(0,0,0,0.4)
    font_color = rgba(255,255,255,1.0)
    placeholder_text = <password>
    fail_color = rgba(255,0,0,0.6)
}

