monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*" }
    ]
    actions = {
      update-props = {
        priority.session = 100
        priority.driver = 100
      }
    }
  }
]

