wireplumber.settings = {
  device.restore-profile = true
  device.restore-routes = true
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "bluez_card.08_12_87_EF_EE_A7" }
    ]
    actions = {
      update-props = {
        priority.session = 2000
        priority.driver = 2000
        bluez5.auto-connect = [ a2dp_sink ]
      }
    }
  }
]

