wireplumber.settings = {
  default-node.auto-switch = true
  default-node.restore = false
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "bluez_card.08_12_87_EF_EE_A7" }
    ]
    actions = {
      update-props = {
        priority.session = 3000
        priority.driver = 3000
        node.pause-on-idle = false
      }
    }
  }
]

