monitor.bluez.rules = [
  {
    matches = [
      { node.name = "~bluez_output.*" }
    ]
    actions = {
      update-props = {
        priority.session = 2000
        priority.driver = 2000
      }
    }
  }
]

