monitor.bluez.rules = [
  {
    matches = [
      { device.name = "bluez_card.08_12_87_EF_EE_A7" }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink ]
        bluez5.profile = "a2dp-sink"
        bluez5.a2dp.codec = "aac"
      }
    }
  }
]

