local vim = vim
local M = {}

-- ==========================
-- HELPER FUNCTIONS
-- ==========================

local function hl_color(name, attr)
	local ok, hl = pcall(vim.api.nvim_get_hl_by_name, name, true)
	if ok and hl[attr] then
		return string.format("#%06x", hl[attr])
	end
	return nil
end

local function contrast_color(hex)
	if not hex or hex == "" then
		return "#ffffff"
	end

	hex = hex:gsub("#", "")
	local r = tonumber(hex:sub(1, 2), 16) or 0
	local g = tonumber(hex:sub(3, 4), 16) or 0
	local b = tonumber(hex:sub(5, 6), 16) or 0

	-- luminance formula
	local lum = 0.299 * r + 0.587 * g + 0.114 * b
	return (lum > 128) and "#000000" or "#ffffff"
end

-- ==========================
-- 1. TMUX PALETTE AUTOGEN
-- ==========================

local function generate_tmux_palette()
	local normal_bg = hl_color("Normal", "background") or "#1e1e2e"
	local normal_fg = hl_color("Normal", "foreground") or "#cdd6f4"

	-- Use bright, visible colors for window index
	local index_bg = hl_color("Function", "foreground")
		or hl_color("Keyword", "foreground")
		or hl_color("String", "foreground")
		or "#89b4fa"

	local index_fg = contrast_color(index_bg)

	return {
		status_bg = normal_bg, -- Use normal background instead of StatusLine
		status_fg = normal_fg, -- Use normal foreground instead of StatusLine
		session_name = hl_color("Title", "foreground") or "#89b4fa",
		index_bg = index_bg,
		index_fg = index_fg,
		name_bg = normal_bg,
		name_fg = normal_fg,
		time_date = hl_color("Comment", "foreground") or "#6c7086",
		battery_icon = hl_color("Constant", "foreground") or "#f38ba8",
		inactive_bg = hl_color("StatusLineNC", "background") or normal_bg,
		inactive_fg = hl_color("StatusLineNC", "foreground") or "#6c7086",
	}
end

local function write_tmux_file(palette)
	local path = os.getenv("HOME") .. "/.config/tmux/tmux_colors.conf"
	local file = io.open(path, "w")
	if not file then
		print("ERROR: Could not open tmux colors file for writing")
		return
	end

	file:write("# ~/.config/tmux/tmux_colors.conf\n")
	file:write("# Auto-generated by Neovim - DO NOT EDIT MANUALLY\n\n")

	-- Write direct tmux settings first
	file:write(string.format("set -g status-bg '%s'\n", palette.status_bg or "#000000"))
	file:write(string.format("set -g status-fg '%s'\n", palette.status_fg or "#000000"))
	file:write("\n")

	-- Write color variables for use in status line
	local vars = {
		"session_name",
		"index_bg",
		"index_fg",
		"name_bg",
		"name_fg",
		"inactive_bg",
		"inactive_fg",
		"time_date",
		"battery_icon",
	}

	for _, k in ipairs(vars) do
		local color = palette[k]
		if not color or color == "" then
			print("WARNING: Missing color for " .. k)
			color = "#000000"
		end
		file:write(string.format("set -g @color_%s '%s'\n", k, color))
	end

	file:flush()
	file:close()
end

local function reload_tmux()
	-- Add small delay to ensure file is fully written, then reload
	os.execute(
		"sleep 0.05 && tmux source-file ~/.config/tmux/tmux_colors.conf 2>/dev/null && tmux source-file ~/.config/tmux/tmux.conf 2>/dev/null &"
	)
end

function M.update_tmux_palette(reload)
	local palette = generate_tmux_palette()
	-- Don't recalculate index_fg, it's already set in generate_tmux_palette

	write_tmux_file(palette)
	if reload then
		reload_tmux()
	end
end

-- ==========================
-- 2. GHOSTTY THEME AUTOGEN
-- ==========================

local function generate_ghostty_theme()
	local normal_bg = hl_color("Normal", "background") or "#1e1e2e"
	local normal_fg = hl_color("Normal", "foreground") or "#cdd6f4"

	-- Get potential cursor colors from multiple sources
	local cursor_candidates = {
		hl_color("Cursor", "background"),
		hl_color("CursorLine", "background"),
		hl_color("Visual", "background"),
		hl_color("IncSearch", "background"),
		hl_color("Search", "background"),
	}

	-- Find first valid cursor color, or use a bright fallback
	local cursor_bg = nil
	for _, color in ipairs(cursor_candidates) do
		if color then
			cursor_bg = color
			break
		end
	end

	-- If still no cursor color, make one that's definitely visible
	if not cursor_bg then
		-- If background is dark, use bright color; if light, use dark
		cursor_bg = contrast_color(normal_bg) == "#ffffff" and "#89b4fa" or "#1e1e2e"
	end

	-- Ensure cursor has maximum contrast with its background
	local cursor_fg = contrast_color(cursor_bg)

	return {
		background = normal_bg,
		foreground = normal_fg,

		-- Cursor - always high contrast and visible
		cursor_color = cursor_bg,
		cursor_text = cursor_fg,

		-- Selection
		selection_background = hl_color("Visual", "background") or "#45475a",
		selection_foreground = hl_color("Visual", "foreground") or normal_fg,

		-- Standard colors (0-7)
		palette = {
			[0] = hl_color("Normal", "background") or "#45475a", -- black
			[1] = hl_color("Error", "foreground") or "#f38ba8", -- red
			[2] = hl_color("String", "foreground") or "#a6e3a1", -- green
			[3] = hl_color("Constant", "foreground") or "#f9e2af", -- yellow
			[4] = hl_color("Function", "foreground") or "#89b4fa", -- blue
			[5] = hl_color("Keyword", "foreground") or "#cba6f7", -- magenta
			[6] = hl_color("Type", "foreground") or "#94e2d5", -- cyan
			[7] = hl_color("Normal", "foreground") or "#bac2de", -- white

			-- Bright colors (8-15)
			[8] = hl_color("Comment", "foreground") or "#585b70", -- bright black
			[9] = hl_color("Error", "foreground") or "#f38ba8", -- bright red
			[10] = hl_color("String", "foreground") or "#a6e3a1", -- bright green
			[11] = hl_color("Constant", "foreground") or "#f9e2af", -- bright yellow
			[12] = hl_color("Function", "foreground") or "#89b4fa", -- bright blue
			[13] = hl_color("Keyword", "foreground") or "#cba6f7", -- bright magenta
			[14] = hl_color("Type", "foreground") or "#94e2d5", -- bright cyan
			[15] = hl_color("Normal", "foreground") or "#cdd6f4", -- bright white
		},
	}
end

local function write_ghostty_file(theme)
	local path = os.getenv("HOME") .. "/.config/ghostty/ghostty_colors.conf"
	local file = io.open(path, "w")
	if not file then
		return
	end

	file:write("# Auto-generated by Neovim - DO NOT EDIT MANUALLY\n\n")

	file:write("background = " .. theme.background .. "\n")
	file:write("foreground = " .. theme.foreground .. "\n\n")

	file:write("cursor-color = " .. theme.cursor_color .. "\n")
	file:write("cursor-text = " .. theme.cursor_text .. "\n\n")

	file:write("selection-background = " .. theme.selection_background .. "\n")
	file:write("selection-foreground = " .. theme.selection_foreground .. "\n\n")

	-- Write palette colors
	for i = 0, 15 do
		file:write(string.format("palette = %d=%s\n", i, theme.palette[i]))
	end

	file:close()
end

local function reload_ghostty()
	-- Ghostty watches config files, so just touching it triggers reload
	os.execute("touch ~/.config/ghostty/ghostty_colors.conf")
end

function M.update_ghostty_theme(reload)
	local theme = generate_ghostty_theme()
	write_ghostty_file(theme)
	if reload then
		reload_ghostty()
	end
end

-- ==========================
-- 3. AUTO-UPDATE ON COLORSCHEME CHANGE
-- ==========================

vim.api.nvim_create_autocmd("ColorScheme", {
	callback = function()
		M.update_tmux_palette(true)
		M.update_ghostty_theme(true)
	end,
})

-- Initial generation
M.update_tmux_palette(false)
M.update_ghostty_theme(false)

-- ==========================
-- 4. FILETYPE AUTOCMDS
-- ==========================

local function setup_markdown_opts()
	vim.opt_local.wrap = true
	vim.opt_local.listchars = { tab = "▸ ", trail = "·" }
	vim.opt_local.formatoptions:append("r")
	vim.opt_local.formatoptions:remove("a")
	vim.opt_local.smartindent = true
	vim.opt.conceallevel = 2
end

vim.api.nvim_create_autocmd("FileType", {
	pattern = { "markdown", "obsidian" },
	callback = setup_markdown_opts,
})

-- ==========================
-- 5. DAILY NOTE COMMAND
-- ==========================

vim.api.nvim_create_user_command("DailyNote", function()
	local date = os.date("%d-%m-%Y")
	local note_path = "/home/krish/vault/journal/" .. date .. ".md"
	local template_path = "/home/krish/vault/templates/daily-journal.md"

	local file = io.open(note_path, "r")
	if not file then
		local template = io.open(template_path, "r")
		if template then
			local content = template:read("*all")
			template:close()
			content = content:gsub("{{date}}", date)

			local new_note = io.open(note_path, "w")
			if new_note then
				new_note:write(content)
				new_note:close()
			end
		end
	else
		file:close()
	end

	vim.cmd("e " .. note_path)
end, {})

return M
